---
- name: Test Playbook
  hosts: all
  become: true
  become_method: sudo
  connections: ssh
  ignore_errors: false
  tasks:
    - name: Task Name Here
      ping: 
    - name: install telnet
      package: 
      name:
        - telnet
        - elinks
        - wget
        - unzip
      state: present
              
      
