---
- name: Playbook for Subnets
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Collect VPC info
      ec2_vpc_net_facts:
        region: "{{region}}"
        filters:
          "tag:QA": VPC
      register: TaskVPC2

    - name: Create Public Subnet 1
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{VPC1.vpcs[0].vpc_id}}"
        region: "{{region}}"
        cidr: "{{Public_cidr1}}"
        resource_tags:
          Name: vpc-task-public
      register: vpc-task-public

    - name: Create Public Subnet 2
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{VPC1.vpcs[0].vpc_id}}"
        region: "{{region}}"
        cidr: "{{Public_cidr2}}"
        resource_tags:
          Name: vpc-task-subnet-2
      register: vpc-task-subnet-2

    - name: Create Public Subnet 3
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{VPC1.vpcs[0].vpc_id}}"
        region: "{{region}}"
        cidr: "{{Public_cidr3}}"
        resource_tags:
          Name: vpc-task-subnet-3
      register: vpc-task-subnet-3