---
- name: To set up internet gateway
  hosts: all
  tasks:
    - name: Create VPC and Subnet
      ec2_vpc:
        state: present
        region: ap-northeast-1
        cidr_block: 10.0.0.0/16
        subnets:
          - cidr: 10.0.0.0/16
            resource_tags: {"Name":"Test Subnet"}
        route_tables:
          - subnets:
            - 10.0.0.0/16
            routes:
              - dest: 0.0.0.0/0
                gw: igw
        wait: yes
        internet_gateway: yes
        resource_tags:
          Name: "Test VPC"
      register: vpc
