---
- name: Loop
  hosts: all
  become: true
  become_method: sudo 
  connections: ssh
  ignor_errors: false
  tasks:
    - name: Loop
      package:
      name: "{{item}}"
      state: present
      with_items:
         - httpd
         - telnet
         - lftp
         - unzip 
         - wget


    - name: Command
      command: "{{item}}" 
      with_items: 
         - "yum install telnet -y" 
           